### ISSUE TITLE
Upgrade Ruby Version?

### ISSUE THREAD

**Issue by dsshap** [stewartlord/serverless-ruby#1]
How would I go about upgrading the ruby version?

**Comment by stewartlord** [comment]
Hi @dsshap, if you check out fetch-ruby.sh, you should see a constant at the top of the file defining the version of Traveling Ruby to use. You can change that to any other version supported by the Traveling Ruby project. Then just run the script and re-deploy.

Let me know if that works for you

**Comment by dsshap** [comment]
Hey @stewartlord thanks for the pointer. Can I ask what is the point on of the `/ruby` directory?

**Comment by stewartlord** [comment]
The `/ruby` directory contains a copy of traveling Ruby that is ready to go. It gets included in the ZIP that is deployed to AWS and then used to execute your script.

**Comment by dsshap** [comment]
Oh, i see now. Its the content of traveling ruby. Thanks!
