### ISSUE TITLE
Adding dependencies

### ISSUE THREAD

**Issue by scottire** [stewartlord/serverless-ruby#4]
What is the best way to add dependencies to a ruby project in AWS Lambda?
I am looking to add `fastlane`.
Thanks

**Comment by ghost** [comment]
@scottire Did you find a solution for this? 

Haven't tried them yet but I've got a couple of ideas 

1. Place your gems in the `serverless-ruby/ruby/lib/ruby/gems/2.2.0/gems` directory
2. Or simply use gem files as ruby modules by cloning them in the root directory. 

One of these ideas should work.

**Comment by scottire** [comment]
No, I never got this solved and moved on to other work. Thanks for the suggestions.

**Comment by desnudopenguino** [comment]
Since the project uses travelling ruby, i'd try walking through the guides over here: https://github.com/phusion/traveling-ruby#getting-started. I'm going to be doing that later today and can report back on how it works.

**Comment by ghost** [comment]
@desnudopenguino Thanks!

**Comment by loweoj** [comment]
Has anyone found a solution to this yet? I'm struggling with the traveling ruby docs...!

**Comment by seeingidog2** [comment]
I was able to get this working without wading into the traveling ruby docs:

```$ gem install --install-dir ruby/lib/ruby/gems/2.2.0 rest-client```

Someone want to add it to this project's docs? 💯
